# Generated by Django 5.1.6 on 2025-11-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationanalysis',
            name='average_response_time',
            field=models.FloatField(default=0, null=True),
        ),
    ]
